### ISSUE TITLE
Bug or not?

### ISSUE THREAD

**Issue by Tomazz95** [DiscordStyles/MinimalCord#1]
Hello,
i just wanted to report a bug (?), if you look at the this screenshot https://i.imgur.com/qzEWAHf.png, you can see that everything apart from the sidebar is the default color. Anyone knows how to fix it please? And also the whole settings are default color aswell.
Thanks in advance

**Comment by Gibbu** [comment]
I was working on the rework and then Discord released this update so I decided to release the rework, meaning there are areas that aren't themes. I'll theme those areas in time.
