### ISSUE TITLE
File downloads do not work after installing theme

### ISSUE THREAD

**Issue by ElektroKill** [DiscordStyles/MinimalCord#10]
After installing this theme the download button on files is no longer clickable. Also, it seems that I can't even get the right-click prompt to appear on files. After some testing, it only happens in a channel I don't have the send permission too and one that is marked with the announcement option.

**Comment by Gibbu** [comment]
Not quite sure how to fix this.

**Comment by ElektroKill** [comment]
AFter some more testing, I think this only happens when I am mentioned in the message.

**Comment by Gibbu** [comment]
That should be fixed then.

**Comment by ElektroKill** [comment]
Yes indeed it’s fixed, thank you!
