### ISSUE TITLE
Minimalcord with light discord look - bugs

### ISSUE THREAD

**Issue by SpeeNNy** [DiscordStyles/MinimalCord#13]
This:
![1](https://user-images.githubusercontent.com/83409986/116558898-33422880-a900-11eb-996e-595c611d4678.png)
Instead of this:
![2](https://user-images.githubusercontent.com/83409986/116558947-3b01cd00-a900-11eb-9434-523efcd37205.png)

and

This:
![3](https://user-images.githubusercontent.com/83409986/116558970-40f7ae00-a900-11eb-92a2-61045b8ee60e.png)
Instead of this:
![4](https://user-images.githubusercontent.com/83409986/116558990-448b3500-a900-11eb-8792-a47aea2c9a5d.png)

I found only these 2 at the moment

Edit:

This:
![5](https://user-images.githubusercontent.com/83409986/116560858-1149a580-a902-11eb-897d-61c41eb02d06.png)
Instead of this:
![6](https://user-images.githubusercontent.com/83409986/116560895-1a3a7700-a902-11eb-89ca-f75b85ec7318.png)

**Comment by Gibbu** [comment]
Fixed.
