### ISSUE TITLE
Message Options Popup Very Small

### ISSUE THREAD

**Issue by toydotgame** [DiscordStyles/MinimalCord#16]
This is probably an intentional design choice.
![image](https://user-images.githubusercontent.com/64190512/119933339-427fc900-bfc7-11eb-9195-067d4ca10d48.png)
I haven't used MinimalCord for about a year and coming back to it the small size is something I find a bit annoying.
Not requesting a change back, but something I can put into my _Custom CSS_ thing to make it normal size again would be very helpful. :)

**Comment by Gibbu** [comment]
Changed it back. No idea why I made them smaller.
