### ISSUE TITLE
[Minor] Textbar text is not aligned properly

### ISSUE THREAD

**Issue by SkrillzPlayz** [DiscordStyles/MinimalCord#17]
![image](https://user-images.githubusercontent.com/42784188/120235798-1d0aed80-c25b-11eb-8e29-917a814a4ba0.png)

As shown in the image, the placeholder text is not aligned with the text in the regular text box, this is not the case on regular discord and is frankly triggering my ocd a lot.

**Comment by Gibbu** [comment]
I didn't really notice it until you pointed it out. I actually triggered me as well. Fixed.
