### ISSUE TITLE
[BUG] Messages are too spaced out.

### ISSUE THREAD

**Issue by DS-GitHub** [DiscordStyles/MinimalCord#19]
![image](https://user-images.githubusercontent.com/37930090/134107372-c5b28e5f-63c4-4290-a094-595e875a6319.png)

**Comment by DS-GitHub** [comment]
normal: 
![image](https://user-images.githubusercontent.com/37930090/134107411-8b7db898-3698-4865-b4b8-75d413f51675.png)

**Comment by weebmode** [comment]
Messages are too spaced out, having the same issue here 😞

![image](https://user-images.githubusercontent.com/90882522/134276435-b2a0edea-312e-4575-8084-9306b7dcef66.png)

**Comment by Gibbu** [comment]
Yep, and there's nothing I can do about it for now.
Discord has just change how the messages are rendered meaning it's not possible to detected which messages are start of a message group or not.

**Comment by DS-GitHub** [comment]
Btw Frosted Glass theme is working properly and showing chats normally.

**Comment by Gibbu** [comment]
Okay? The reason for that is because Frosted Glass doesn't change the messages. Like at all.

**Comment by DS-GitHub** [comment]
ah..

**Comment by Gibbu** [comment]
I fixed it.
