### ISSUE TITLE
Themes not working on latest versions of canary.

### ISSUE THREAD

**Issue by BrianMSK** [DiscordStyles/MinimalCord#23]
**Describe the bug**  
Within the new versions of discord on Canary branch, all the themes are broken because of changed class naming.

**To Reproduce**  
Download and install latest discord canary, and betterdiscord, enable themes.

**Screenshots**  
https://i.imgur.com/b668YAG.png
https://i.imgur.com/2apicHu.png
https://i.imgur.com/2Rz6Fsh.png
https://i.imgur.com/PPXeV91.png

**Infomation (please complete the following information):**  
Discord channel: Canary
OS: WIndows
Mod: BetterDiscord
Discord language: English, UK

**Comment by Gibbu** [comment]
Correct the newest Cancary version has changed a lot of things. And won't be fixed until it comes to Stable.
Discord has a history of updating, reverting, updating, changing in span of a couple of hours to days.

It's pretty much a waste of time to actively support Canary.
