### ISSUE TITLE
A recent update broke many themes, this one included.

### ISSUE THREAD

**Issue by Elevatorman1** [DiscordStyles/MinimalCord#24]
**Describe the bug**  
*The theme now only changes very few aspects of discord and is mostly broken*  

**To Reproduce**  
*use the theme*  

**Screenshots**  
*https://imgur.com/a/yFWHk2s*  

**Infomation (please complete the following information):**  
Discord channel: *Stable*  
OS: *Windows/Linux/OSX*  
Mod: *BetterDiscord*  
Discord language: *English*

**Comment by Gibbu** [comment]
Fixed. Re-enable your theme.
