### ISSUE TITLE
Difficult to see spoiler text

### ISSUE THREAD

**Issue by mfsoup** [DiscordStyles/MinimalCord#25]
Because the theme is much darker than regular Discord dark mode, it's quite difficult to see spoiler text. The contrast would be much better if the boxes were lightened or darkened.

![spoiler normal](https://user-images.githubusercontent.com/38110452/157998315-4306f34f-2fc0-49cf-a36e-ddb50bc8cf58.png)
![spoiler minimal](https://user-images.githubusercontent.com/38110452/157998316-15661c73-d6b3-44c9-ac36-b96f835f3960.png)

**Comment by Gibbu** [comment]
Fixed ages ago, forgot to close.

**Comment by mfsoup** [comment]
I think Discord changed something and this is now a problem again.
