### ISSUE TITLE
Brief description of the bug

### ISSUE THREAD

**Issue by MEWPASCO** [DiscordStyles/MinimalCord#27]
### Describe the bug
*A clear and concise description of what the bug is*  
New Text in Voice Chat got rolled out and needs the little touch of the minimal cord look, since most Servers tend to actually use this feature instead of the old voice chats we discord admins created

### To Reproduce  
*Steps to reproduce the behavior*  
Hop in a VC, enable the text chat and it shows in the simple discord grey look

### Screenshots
*If applicable, add screenshots to help explain your problem*
Attached

### Infomation (please complete the following information)
**Discord channel**: *PTB*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*  

![image](https://user-images.githubusercontent.com/50899079/172136021-e80646e6-6c31-48e2-a25c-ed4dc95fc0a3.png)

**Comment by Gibbu** [comment]
Fixed with new forums.
