### ISSUE TITLE
Pinned messages get cut off

### ISSUE THREAD

**Issue by Joseph-Seed-18** [DiscordStyles/MinimalCord#28]
### Describe the bug
When looking at pins, the pinned messages look like they get cut off at places they shouldn't be.

### To Reproduce  
1. Open any server and go to channel with pinned messages
2. Open pinned messages

### Screenshots
![Screenshot 2022-08-11 141259](https://user-images.githubusercontent.com/111084825/184220760-d10f8632-e4c5-4e84-be3e-c9beca10fbec.png)
![Screenshot 2022-08-11 140845](https://user-images.githubusercontent.com/111084825/184220762-489a40d4-a845-4866-8610-8e9acd120efc.png)
(Both screenshots are from the theme support server)

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*

**Comment by Gibbu** [comment]
Fixed
