### ISSUE TITLE
Weird visual glitch in status menu

### ISSUE THREAD

**Issue by Joseph-Seed-18** [DiscordStyles/MinimalCord#29]
### Describe the bug
The color of the profile in the status menu gets cut off towards the right, issue doesn't exist elsewhere.

### To Reproduce  
1. Click on profile 

### Screenshots

![Screenshot 2022-08-11 142216](https://user-images.githubusercontent.com/111084825/184243684-71732622-b77f-42a6-bae3-511da2cb10f3.png)
![image_2022-08-11_161508619](https://user-images.githubusercontent.com/111084825/184243528-0c18582c-1781-4943-934f-71933d2c28b9.png)

(Top image is with MinimalCord theme turned on, bottom image is MinimalCord theme turned off. Visual glitch is circled in green in top image)

### Infomation (please complete the following information)
**Discord channel**: *Stable*  
**OS**: *Windows*  
**Mod**: *BetterDiscord*  
**Discord language**: *English*

**Comment by Gibbu** [comment]
Should be "fixed" since Discord are doing their redesign stuff.
