### ISSUE TITLE
Mention message on chat does not color properly

### ISSUE THREAD

**Issue by giuliotoplad** [DiscordStyles/MinimalCord#4]
![image](https://user-images.githubusercontent.com/36372281/99131521-b05c3880-2613-11eb-8e6a-8a45a7055e66.png)

If someone in chat mention me and write a message longer than one line a piece of the container of the chat does not color properly

**Comment by Gibbu** [comment]
I have two options:
1. Apply the mention to the whole message container.
2. Apply the mention to just the text.

Discord message structure is very limiting.

**Comment by giuliotoplad** [comment]
> I have two options:
> 
> 1. Apply the mention to the whole message container.
> 2. Apply the mention to just the text.
> 
> Discord message structure is very limiting.

The best option for fix this is the first option (Apply the mention to the whole message container)

**Comment by Gibbu** [comment]
The first option is what it is currently. I cannot make it span over multiple messages.
As I said above
> Discord message structure is very limiting.

**Comment by giuliotoplad** [comment]
Ok I understand
