### ISSUE TITLE
Message right under mention is positioned too high

### ISSUE THREAD

**Issue by yamiM0NSTER** [DiscordStyles/MinimalCord#7]
As title points out if there is a message right under a mention message the text/emote will appear over mention edge. Examples:
![obraz](https://user-images.githubusercontent.com/22958062/99871386-52fb5500-2bda-11eb-87a2-cacff081a05b.png)
![obraz](https://user-images.githubusercontent.com/22958062/99871394-65758e80-2bda-11eb-9f4a-349aed1d120f.png)

It seems that code in this clause is causing the issue:
https://github.com/DiscordStyles/MinimalCord/blob/master/base.css#L299

By disabling either one of those, the messages display way better. Maybe it's needed for something else but I don't know what that would be.

Cheers!

**Comment by Gibbu** [comment]
L299 is used to provide even spacing between messages.
Without it, it will look like this:
![image](https://user-images.githubusercontent.com/20338746/99889084-39274400-2ca6-11eb-9176-c67646b19e9f.png)

I think the only way to fix the mentions is to make the mention colour wrap around the text, not the container.
Like so:
![image](https://user-images.githubusercontent.com/20338746/99889345-4c3b1380-2ca8-11eb-9bce-3ee281912298.png)

**Comment by yamiM0NSTER** [comment]
Yeah, if L299 is needed then wrapping text seems like the solution.

**Comment by yamiM0NSTER** [comment]
On another note: Won't it break embeds though?

**Comment by Gibbu** [comment]
Nah, it's fine
![image](https://user-images.githubusercontent.com/20338746/99900092-feeb9000-2d01-11eb-8501-2d64fff89c50.png)

**Comment by yamiM0NSTER** [comment]
I guess that's the way to go then, until discord team changes something.
