### ISSUE TITLE
Profile image goes over text in chat

### ISSUE THREAD

**Issue by tomasdincau** [DiscordStyles/MinimalCord#8]
![image](https://user-images.githubusercontent.com/49094495/99877868-da13f180-2c09-11eb-8364-fa1bbb87f634.png)
In this way.

**Comment by yamiM0NSTER** [comment]
I had that issue with old theme file from archived repository, downloading updated one fixed the issue for me.

**Comment by Gibbu** [comment]
As yami said: Redownload.
